// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddPinReducer from "../add_pin_reducer";
import AdminSetOrganisationReducer from "../admin_set_organisation_reducer";
import DeleteModuleReducer from "../delete_module_reducer";
import DriveRoverReducer from "../drive_rover_reducer";
import EnterReducer from "../enter_reducer";
import HideCursorReducer from "../hide_cursor_reducer";
import JoinReducer from "../join_reducer";
import MoveModuleReducer from "../move_module_reducer";
import PlaceModuleReducer from "../place_module_reducer";
import RemoveConceptReducer from "../remove_concept_reducer";
import RemovePinReducer from "../remove_pin_reducer";
import RenamePinReducer from "../rename_pin_reducer";
import ResetRoverReducer from "../reset_rover_reducer";
import RoverArrivedReducer from "../rover_arrived_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetModuleScoreReducer from "../set_module_score_reducer";
import SetSceneReducer from "../set_scene_reducer";
import ShareConceptReducer from "../share_concept_reducer";
import SignInReducer from "../sign_in_reducer";
import SignOutReducer from "../sign_out_reducer";
import UpdateCursorReducer from "../update_cursor_reducer";

export type AddPinParams = __Infer<typeof AddPinReducer>;
export type AdminSetOrganisationParams = __Infer<typeof AdminSetOrganisationReducer>;
export type DeleteModuleParams = __Infer<typeof DeleteModuleReducer>;
export type DriveRoverParams = __Infer<typeof DriveRoverReducer>;
export type EnterParams = __Infer<typeof EnterReducer>;
export type HideCursorParams = __Infer<typeof HideCursorReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type MoveModuleParams = __Infer<typeof MoveModuleReducer>;
export type PlaceModuleParams = __Infer<typeof PlaceModuleReducer>;
export type RemoveConceptParams = __Infer<typeof RemoveConceptReducer>;
export type RemovePinParams = __Infer<typeof RemovePinReducer>;
export type RenamePinParams = __Infer<typeof RenamePinReducer>;
export type ResetRoverParams = __Infer<typeof ResetRoverReducer>;
export type RoverArrivedParams = __Infer<typeof RoverArrivedReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetModuleScoreParams = __Infer<typeof SetModuleScoreReducer>;
export type SetSceneParams = __Infer<typeof SetSceneReducer>;
export type ShareConceptParams = __Infer<typeof ShareConceptReducer>;
export type SignInParams = __Infer<typeof SignInReducer>;
export type SignOutParams = __Infer<typeof SignOutReducer>;
export type UpdateCursorParams = __Infer<typeof UpdateCursorReducer>;

