// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sceneId: __t.string().name("scene_id"),
  author: __t.identity(),
  authorName: __t.string().name("author_name"),
  renderId: __t.string().name("render_id"),
  idea: __t.string(),
  prompt: __t.string(),
  poseJson: __t.string().name("pose_json"),
  image: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
