// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  sceneId: __t.string().name("scene_id"),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  camX: __t.f64().name("cam_x"),
  camY: __t.f64().name("cam_y"),
  camZ: __t.f64().name("cam_z"),
  dirX: __t.f64().name("dir_x"),
  dirY: __t.f64().name("dir_y"),
  dirZ: __t.f64().name("dir_z"),
  updatedAt: __t.timestamp().name("updated_at"),
});
