// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sceneId: __t.string().name("scene_id"),
  author: __t.identity(),
  type: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  rotationZDeg: __t.f64().name("rotation_z_deg"),
  scale: __t.f64(),
  scoreJson: __t.string().name("score_json"),
  updatedAt: __t.timestamp().name("updated_at"),
});
