// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
});
export type Admin = __Infer<typeof Admin>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sceneId: __t.string(),
  author: __t.identity(),
  name: __t.string(),
  color: __t.string(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const Concept = __t.object("Concept", {
  id: __t.u64(),
  sceneId: __t.string(),
  author: __t.identity(),
  authorName: __t.string(),
  renderId: __t.string(),
  idea: __t.string(),
  prompt: __t.string(),
  poseJson: __t.string(),
  image: __t.string(),
  createdAt: __t.timestamp(),
});
export type Concept = __Infer<typeof Concept>;

export const Cursor = __t.object("Cursor", {
  identity: __t.identity(),
  sceneId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  camX: __t.f64(),
  camY: __t.f64(),
  camZ: __t.f64(),
  dirX: __t.f64(),
  dirY: __t.f64(),
  dirZ: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type Cursor = __Infer<typeof Cursor>;

export const Member = __t.object("Member", {
  identity: __t.identity(),
  name: __t.string(),
  orgId: __t.string(),
  joinedAt: __t.timestamp(),
});
export type Member = __Infer<typeof Member>;

export const MyScenes = __t.object("MyScenes", {});
export type MyScenes = __Infer<typeof MyScenes>;

export const Organisation = __t.object("Organisation", {
  id: __t.string(),
  name: __t.string(),
});
export type Organisation = __Infer<typeof Organisation>;

export const OrganisationSecret = __t.object("OrganisationSecret", {
  orgId: __t.string(),
  code: __t.string(),
});
export type OrganisationSecret = __Infer<typeof OrganisationSecret>;

export const Pin = __t.object("Pin", {
  id: __t.u64(),
  sceneId: __t.string(),
  author: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  note: __t.string(),
  createdAt: __t.timestamp(),
});
export type Pin = __Infer<typeof Pin>;

export const PlacedModule = __t.object("PlacedModule", {
  id: __t.u64(),
  sceneId: __t.string(),
  author: __t.identity(),
  type: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  rotationZDeg: __t.f64(),
  scale: __t.f64(),
  scoreJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PlacedModule = __Infer<typeof PlacedModule>;

export const Rover = __t.object("Rover", {
  sceneId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  targetX: __t.f64(),
  targetY: __t.f64(),
  targetLabel: __t.string(),
  driving: __t.bool(),
  driver: __t.identity(),
  seq: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type Rover = __Infer<typeof Rover>;

export const SceneAccess = __t.object("SceneAccess", {
  id: __t.u64(),
  orgId: __t.string(),
  sceneId: __t.string(),
});
export type SceneAccess = __Infer<typeof SceneAccess>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  color: __t.string(),
  activeSceneId: __t.string(),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

